### ISSUE TITLE
streaming transcription: Add example

### ISSUE THREAD

**Issue by powellnorma** [fedirz/faster-whisper-server#15]
I first thought that `It works in the similar way to chat messages are being when chatting with LLMs.` means it would use SSE too. But it just streams raw json. However its not even always a complete json object, sometimes its just part of one. Or am I missing something?

I currently just do:
```py
with requests.post(url, files=files, data=data, stream=True) as r:
    for x in r:
```

**Comment by powellnorma** [comment]
Ok, this seems to work:

```py
with requests.post(url, files=files, data=data, stream=True) as r:
    tmp = b""
    for x in r:
        tmp += x
        if tmp[-1] == b'}':
            txt = json.loads(tmp)['text']
            print(txt)
```

**Comment by fedirz** [comment]
Let me test out the behaviour and get back to you. The first you provided is how it should work

**Comment by fedirz** [comment]
SSE should work as expected now!
