### ISSUE TITLE
允许模型长期挂载

### ISSUE THREAD

**Issue by JustAlias** [fedirz/faster-whisper-server#150]
增加环境变量，允许docker的模型长期挂载，除非有新的请求挂载其他模型

docker的网页加载模型时，尝试加载本地模型，以适应离线环境

**Comment by JustAlias** [comment]
ttl=-1   haha

**Comment by yijiegao2006** [comment]
请教一下，怎么在docker 里改变ttl 的数值？查了一下chatgpt 需要定义环境变量，而且环境变量需要放在config.py里。但是docker 是整个下载现有的文件，没有改动，不知道怎么处理这种情况。
