### ISSUE TITLE
Can I use a public url instead of a local file?

### ISSUE THREAD

**Issue by chriso0710** [fedirz/faster-whisper-server#154]
I would like to use the API with curl. 
Any chance to provide a public url for the audio file instead of a local file?

Thanks
Christian

**Comment by fedirz** [comment]
This functionality isn't supported. 

I see the appeal in this functionality from an ease of use perspective, but there are two problems I see with implementing it
1. Not a security expert, but this seems like it would open up room for some vulnerabilities.
2. A lot of websites, YouTube in particular, actively prevent you from simple downloading the videos, meaning this feature won't work for a number of websites.
