### ISSUE TITLE
Use multiple GPUs to process queue

### ISSUE THREAD

**Issue by theodufort** [fedirz/faster-whisper-server#156]
I am trying to use both of my GPUs who are passed through to my docker container.
`services:
  faster-whisper-server-cuda:
    image: fedirz/faster-whisper-server:latest-cuda
    build:
      dockerfile: Dockerfile.cuda
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    restart: unless-stopped
    ports:
      - 8162:8000
    environment:
      - WHISPER__MODEL=deepdml/faster-whisper-large-v3-turbo-ct2
      - WHISPER__INFERENCE_DEVICE=cuda
      - WHISPER__COMPUTE_TYPE=int8
      - WHISPER__NUM_WORKERS=4
      - WHISPER__CPU_THREADS=4
      - WHISPER_DEVICE=cuda
      - DEFAULT_LANGUAGE=en
      - PRELOAD_MODELS=["deepdml/faster-whisper-large-v3-turbo-ct2"]
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  hugging_face_cache:`
  
  I tried everything but it won't use more than 1 GPU even if:
![image](https://github.com/user-attachments/assets/88c99280-c196-4799-929e-db5f92afa7d7)

**Comment by fedirz** [comment]
[This](https://github.com/fedirz/faster-whisper-server/blob/155907f788a179c35410e77ef20a306132c7d77f/src/faster_whisper_server/config.py?plain=1#L161) is the config options which controls which GPUs the model runs on. The default index is `0`. You'll want to set it to an array like so `WHISPER__DEVICE_INDEX='[0, 1]'`. If this doesn't help, re-open the issue.

Relevant pydantic-settings [docs](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#parsing-environment-variable-values)
