### ISSUE TITLE
Support vtt and srt response types

### ISSUE THREAD

**Issue by fedirz** [fedirz/faster-whisper-server#16]
https://platform.openai.com/docs/api-reference/audio/createTranscription#audio-createtranscription-response_format

**Comment by cichy3000** [comment]
This would be great, if the model would support str/vtt 🤞

**Comment by fedirz** [comment]
Yep, you should be able to do that.

May I ask what's your use case for VTT/SRT response types, genuinely curios since I haven't these formats before besides in the OpenAI's API reference

**Comment by Ki-er** [comment]
> May I ask what's your use case for VTT/SRT response types

VTT is the file that zoom audio transcripts come in, I see them during my interviews on zoom. This is a text file though not an audio file format as far as I know. I am not familiar with SRT.

**Comment by csernikmarton** [comment]
Hi @fedirz, when is this feature expected to become available in a tagged version and then in the Docker image? Thanks!

**Comment by fedirz** [comment]
Hey, I know it's pretty late, but I just pushed a new tag.
