### ISSUE TITLE
the model name gives error

### ISSUE THREAD

**Issue by Bikram9035** [fedirz/faster-whisper-server#17]
hello fedirz,

audio_file= open("recorded_audio.wav", "rb")
transcription = gpt.audio.transcriptions.create(
  model="Systran/faster-distil-whisper-large-v3", 
  file=audio_file
)
tts= transcription.text

am getting error when using the model name with offical openai whisper api
raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'invalid model ID', 'type': 'invalid_request_error', 'param': None, 'code': None}}

am new to this api and things so please help because there lot of overwhelming miss information online but am super excited to make this work. Hope u will understand my situation

os:windows.
vscode,python:3.12.2

Thank you.

**Comment by fedirz** [comment]
Hey, are you setting OPENAI_API_KEY and OPENAI_API_BASE  environment variables?

**Comment by Bikram9035** [comment]
yeah I did setup openaikey in .env file but don't know what to write in OPENAI_API_BASE URL , and from where do i find that link from the official openai website please lemme know.

**Comment by fedirz** [comment]
See [this](https://github.com/gridware/gridware-bytes/pull/2428) section of the README, it should help

**Comment by fedirz** [comment]
You'll need to spin up `faster-whisper-server` using Docker, and your `base_url` would be `http://localhost:8000/v1/`. In your code, you are using the OpenAI's URL.

**Comment by kippytech** [comment]
Hey Fedirz,
Is it also compatible with openai SDK for Nodejs? And if so, in your example you used API key as a string that implied not leaving it empty. Does it mean I just have to put anything so long as it's a string probably to avoid an error?

**Comment by fedirz** [comment]
> Hey Fedirz, Is it also compatible with openai SDK for Nodejs? And if so, in your example you used API key as a string that implied not leaving it empty. Does it mean I just have to put anything so long as it's a string probably to avoid an error?

Yes

**Comment by Gan-Xing** [comment]
Hi @Bikram9035 and @fedirz,

I have implemented a solution for using custom models with the faster-whisper-server. Here’s a brief overview of my setup and workflow:

### Main Project Overview

1. **Frontend**:
    - The frontend application allows users to select different models and languages for transcription and translation.
    - Users can either record audio in real-time or upload audio files.
    - The frontend communicates with the backend via WebSocket to send audio data and receive transcriptions or translations.

2. **Backend**:
    - The backend is built with Node.js and uses WebSocket for real-time communication.
    - Audio files are received, converted to WAV format using `ffmpeg`, and split into chunks using a Python script.
    - The backend then sends these audio chunks to the transcription service and returns the results to the frontend.
    - The backend also supports translation requests using an external translation API.

You can find the full implementation and detailed instructions in my repository [here](https://github.com/Gan-Xing/whisper).

### Simplified Example (whisper-html)

For a simpler example that connects directly to the faster-whisper-server via WebSocket, you can refer to my `whisper-html` project. This project demonstrates a straightforward way to send audio data and receive transcriptions using only HTML and JavaScript.

You can find the `whisper-html` project [here](https://github.com/Gan-Xing/whisper-html/blob/main/public/index.html).

Feel free to reach out if you have any questions or need further assistance.

Best regards,

[Gan-Xing]
