### ISSUE TITLE
Call from Home Assistant and GPU issue

### ISSUE THREAD

**Issue by denisjoshua** [fedirz/faster-whisper-server#173]
Hi there all, 
I have just installed the docker version os FWS and if I understand is use uses [faster-whisper](https://github.com/SYSTRAN/faster-whisper) as its backend. 
Before I had installed [faster-whisper](https://github.com/SYSTRAN/faster-whisper) and was working for calls from Home Assistant.
But this time the calls is not working... 

Is there something I miss please ? 
Can be that the Faster Whisper Server don't have the Wyoming protocol ? 

Also it didn't find my GPU using same compose script like in faster-whisper (where the GPU it's work? 

Thanks a lot. 
Denis

**Comment by fedirz** [comment]
> Can be that the Faster Whisper Server don't have the Wyoming protocol ?
Correct, this project doesn't support it. Instead this project provides an OpenAI-compatible API

> Also it didn't find my GPU using same compose script like in faster-whisper (where the GPU it's work?
If you are using Docker, you'll need to configure it to detect GPUs. See [this](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

**Comment by Cicatr1x** [comment]
@fedirz Do you know an integration working with the OpenAI API that we could use in Home Assistant?

**Comment by fedirz** [comment]
@Cicatr1x I don't know, as I don't use HA myself. You might find a better answer on HA community, HA subreddit, or [LocalLLaMA](https://www.reddit.com/r/LocalLLaMA/)

**Comment by citgot** [comment]
Is it possible to integrate the Wyoming protocol and still keep the OpenAI API? As of right now it seems that there are no ways of using Speaches TTS for home assistant. So you still need a separate Piper running which is not ideal.

**Comment by citgot** [comment]
I update with my solutions for the lack of Wyoming protocol IF someone finds this in the future. 

The following Home assistant integrations will make whisper and piper work with the API. 

https://github.com/fabio-garavini/ha-openai-whisper-stt-api

https://github.com/sfortis/openai_tts

**Comment by Cicatr1x** [comment]
> I update with my solutions for the lack of Wyoming protocol IF someone finds this in the future.
> 
> The following Home assistant integrations will make whisper and piper work with the API.
> 
> https://github.com/fabio-garavini/ha-openai-whisper-stt-api
> 
> https://github.com/sfortis/openai_tts

Did you try that with speaches-ai as Well?

**Comment by Cicatr1x** [comment]
Ok i was a bit confused as both need a valid OpenAI API Key. Could you elaborate a bit how and what exactly you configured to make it work with speaches-ai?

**Comment by citgot** [comment]
You need for the integrations to point the URL to your Speaches-AI IP and port and then use the same ending as the original URL. Then it is totally local and you can write whatever in the API field.

-------- Ursprungligt meddelande --------
Den 2025-02-07 09:40, Cicatr1x  skrev:
