### ISSUE TITLE
whisper timestamp doesn't match with vad result

### ISSUE THREAD

**Issue by heheda166** [fedirz/faster-whisper-server#43]
**VAD result:**
`Speech timestamps: [{'start_time': 21.14, 'end_time': 26.83}, {'start_time': 26.83, 'end_time': 32.75}, {'start_time': 72.82, 'end_time': 78.8}, {'start_time': 110.54, 'end_time': 111.66}, {'start_time': 111.66, 'end_time': 122.32}, {'start_time': 154.19, 'end_time': 157.49}, {'start_time': 157.49, 'end_time': 160.35}, {'start_time': 160.35, 'end_time': 166.64}, {'start_time': 189.9, 'end_time': 190.99}]`
**Whisper result:**
```
[TranscriptionVerboseJsonResponse(
    task='transcribe',
    language='en',
    duration=192.84,
    words=[],
    segments=[
        SegmentObject(id=1, seek=2876, start=21.14, end=26.24, tokens=[50365, 876, 11, 286, 1604, 291, 13, 2908, 11, 286, 920, 362, 512, 22618, 466, 7214, 13, 50620], temperature=0.0, avg_logprob=-0.14888649528053985, compression_ratio=1.6180257510729614, no_speech_prob=0.006687164306640625), 
        SegmentObject(id=2, seek=2876, start=27.06, end=32.24, tokens=[
            50661, 286, 2198, 300, 7214, 2115, 366, 588, 3997, 293, 2171, 406, 1858, 281, 10724, 13, 50920], temperature=0.0, avg_logprob=-0.14888649528053985, compression_ratio=1.6180257510729614, no_speech_prob=0.006687164306640625),
        SegmentObject(id=3, seek=2876, start=32.5, end=78.22, tokens=[
            50933, 1664, 291, 2748, 512, 7214, 3383, 300, 366, 12873, 337, 385, 293, 452, 1605, 30, 51216], temperature=0.0, avg_logprob=-0.14888649528053985, compression_ratio=1.6180257510729614, no_speech_prob=0.006687164306640625)])]
```

**vad detect speech from 72.82 to 78.8, but the result of whisper from 32.5 to 78.22**

**Comment by fedirz** [comment]
I can look into this if you provide with additional details. Please send an audio file, the model you are using, the route being used, and the output you are getting and the output you are expecting (assuming it's different from what's already in the issue).
