### ISSUE TITLE
Having interal server error when having massive request

### ISSUE THREAD

**Issue by Ltitor** [fedirz/faster-whisper-server#45]
[log3.txt](https://github.com/user-attachments/files/16464611/log3.txt)
[logs3.txt](https://github.com/user-attachments/files/16465206/logs3.txt)

Maybe i'm dumb. I was trying to make a transcribe task and there are lot of them. I encounter this problem. Should I just make my request less?

**Comment by Ltitor** [comment]
i'm dumb. I just confirmed it was the server problem when i request too many times (using a for loop)

**Comment by Ltitor** [comment]
I just debugged again. I just found what cause the error. It turns out if the model cannot detect anything, it just straight throwing out 500 error without explaining when using API.

**Comment by fedirz** [comment]
>  It turns out if the model cannot detect anything, it just straight throwing out 500 error without explaining when using API.

Please elaborate

From the logs, it's not immediately clear to me what's causing the error. It'd be helpful if you could provide the arguments you are sending in the POST request.

Also, are you sending requests in a loop sequentially or are you requesting multiple transcriptions at the same time (e.g. `asyncio.gather(*[client.post(...) for _ in range(n)])`)?

**Comment by Ltitor** [comment]
> > It turns out if the model cannot detect anything, it just straight throwing out 500 error without explaining when using API.
> 
> Please elaborate
> 
> From the logs, it's not immediately clear to me what's causing the error. It'd be helpful if you could provide the arguments you are sending in the POST request.
> 
> Also, are you sending requests in a loop sequentially or are you requesting multiple transcriptions at the same time (e.g. `asyncio.gather(*[client.post(...) for _ in range(n)])`)?

thanks for your reply.
[log4.txt](https://github.com/user-attachments/files/16475102/log4.txt)
the log4.txt show my local debug log

I was sending request using OpenAI api as listed in the # usage in a `for` loop sequentially.
I figured out when the model cannot return anything, the server actually return 500 instead of `None`
Because of the poor exception handling mechanism on my local end, I thought i have too much request and or something goes wrong on the server side.
