### ISSUE TITLE
[Feature] Set default model with env variable in docker

### ISSUE THREAD

**Issue by defaultsecurity** [fedirz/faster-whisper-server#46]
Would it be possible to expose the variable WHISPER_MODEL, so when we start the docker container we can define the default model? It would be useful when using services that don't ask the default model in their queries.

_Thus we could start the container with a command similar to this:_
```
docker run --env model="Systran/faster-whisper-medium.en" fedirz/faster-whisper-server:latest-cuda
```

I really love this server. Fast and effective. Thank you for your hard work and time.

**Comment by fedirz** [comment]
Already possible, setting `WHISPER__MODEL` will achieve this behavior.  See `Config` class in `config.py` for other options.

**Comment by defaultsecurity** [comment]
@fedirz 
Thank you for the clarification. It worked.

I'm also trying to restrict the default language, but can't seem to. I'm running the container with this command:
```
docker run --env LOG_LEVEL="debug" --env WHISPER__MODEL="Systran/faster-whisper-large-v3" --env DEFAULT_LANGUAGE="en" fedirz/faster-whisper-server:latest-cuda
```
Any suggestions?
