### ISSUE TITLE
feature request: add CORS support

### ISSUE THREAD

**Issue by braden-w** [fedirz/faster-whisper-server#48]
Add CORS support, loaded from CORS_ORIGINS in env. I've opened a WIP pull request in #47. This is useful for enabling browsers to directly request to the local faster-whisper-server, as currently they are blocked unless they use an intermediate server endpoint.

Invocations from the browser are currently blocked unless CORS is set. For now, I'm proxying requests via a rust backend function (I'm using Tauri).

Any help with how to integrate and pass environment variables in the docker images? I'm not a docker expert and am unsure how to best continue.

**Comment by fedirz** [comment]
#50

**Comment by braden-w** [comment]
Thank you very much!
