### ISSUE TITLE
A few questions 

### ISSUE THREAD

**Issue by mru4913** [fedirz/faster-whisper-server#49]
Thanks for the great work.

I have a few questions:
- Is it possible to optimized with concurrency inferences?
- Is it better to add sync def for FastAPI entry point?
- How to scale up to 100 users using websockets with fasterwshiper.
---
others: 
- `from openai import OpenAI, AsyncOpenAI` does not support stream argument, which should be mentioned 
-  it will be nice to have num_workers.

**Comment by fedirz** [comment]
1. Not sure what you mean here. 
2. Are you referring to functions handling web sockets?
3. Haven't tested with more than one connection myself.
4. From README.md: "Unlike OpenAI's API, faster-whisper-server also supports streaming transcriptions(and translations). ". It could probably be made clearer, but it's there.
5. You should be able to configure that using environment variables. From [uvicorn docs](https://www.uvicorn.org/deployment/#running-from-the-command-line)
```
  --workers INTEGER               Number of worker processes. Defaults to the
                                  $WEB_CONCURRENCY environment variable if
                                  available, or 1. Not valid with --reload.
```

**Comment by mru4913** [comment]
Thank you for your reply.

> Not sure what you mean here.
-  As for concurrency inferences, I mean dynamic  batching  or static batching inference in  a single instance on a GPU. Batching inference speeds up the entire pipeline.

> Are you referring to functions handling web sockets?
- I have read your source code and I did not see `asyn` in front of  transcriptions`def`. Is this on purpose?

**Comment by RonanKMcGovern** [comment]
@mru4913 did you find any way to do concurrency?

In principle, submitting a batch of requests should be easy for the model to handle - but openai style requests won't handle that...

Dynamic batching would be more complex (something like vLLM) but definitely would be very interesting as an open source offering.

LMK if you find any hacks to get either working. Thanks.

And thanks @fedirz for making this repo, just started working with it today and things have being working without a hitch.
