### ISSUE TITLE
Device index for multiple gpus

### ISSUE THREAD

**Issue by Nyralei** [fedirz/faster-whisper-server#51]
Hello.
I have a feature request: faster-whisper supports setting device_index in WhisperModel class.
https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L607
Currently faster-whisper-server doesn't support it without modification of source code.
Would be great to have an option to set other attributes too

**Comment by fedirz** [comment]
Will add support for this sometime this week.
