### ISSUE TITLE
Invalid HTTP request received, when open-webui posts microphone audio to faster-whisper-server

### ISSUE THREAD

**Issue by johnyu0** [fedirz/faster-whisper-server#54]
**open-webui STT configuration:**
![image](https://github.com/user-attachments/assets/85056b34-30bf-43f0-a238-d37058c06056)

**faster-whisper-server‘s log:**
![image](https://github.com/user-attachments/assets/9aa26742-e7ba-4727-9b01-85025d448eb7)

**browser's logs:**
![image](https://github.com/user-attachments/assets/b3ec8f90-6fbd-4b68-b5b9-4bc991a5ec9e)

**brower's network logs:**
![image](https://github.com/user-attachments/assets/df9423d7-c7f6-4335-946e-9475d29c18ec)

Request URL:
https://ainusre.shenzhuo.vip/audio/api/v1/transcriptions
Request Method:
POST
Status Code:
400 Bad Request
Remote Address:
115.231.220.17:443
Referrer Policy:
strict-origin-when-cross-origin
Access-Control-Allow-Credentials:
true
Access-Control-Allow-Origin:
https://ainusre.shenzhuo.vip
Content-Length:
78
Content-Type:
application/json
Date:
Wed, 14 Aug 2024 01:38:58 GMT
Server:
uvicorn
Vary:
Origin, Origin
X-Process-Time:
0
Accept:
application/json
Authorization:
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhOGIyYzMyLTIzNjQtNGE2NC1iZWI3LTQyYjdjZTg5MDAwYyJ9.Z8rHxhmQ9iiWG9KhcLcIXZphdLPrDVaFkFkL5bqfyIY
Content-Type:
multipart/form-data; boundary=----WebKitFormBoundaryuLcFLPPrPP1D9lRZ
Dnt:
1
Referer:
https://ainusre.shenzhuo.vip/c/b0992e08-5217-40e5-ad31-4dcdbfe47e1f/
Sec-Ch-Ua:
"Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
Sec-Ch-Ua-Mobile:
?1
Sec-Ch-Ua-Platform:
"Android"
User-Agent:
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36

**Comment by fedirz** [comment]
The requested URL is incorrect. Should be `/v1/audio/transcriptions` instead of `/audio/api/v1/transcriptions`

**Comment by johnyu0** [comment]
It's not the reason. I found the error configuration of https. It's should be http://192.168.1.241/v1
