### ISSUE TITLE
What is the minimum/optimal hardware requirements?

### ISSUE THREAD

**Issue by mabdelfattah** [fedirz/faster-whisper-server#56]
I want to use faster-whisper-server on one of Hetzner servers, but I'm not sure which one to choose! Should I go for CPU (Arm) or GPU (Nvidia RTX™ 4000)? Furthermore, what are the minimum memory requirements?

**Comment by fedirz** [comment]
It all depends on your use case. If you have need real-time audio transcription using one of the large models, I'd recommend using a GPU. However, `faster-whisper` also runs pretty well on a CPU, so if you are ok with waiting a bit longer for a transcription and/or using a smaller model. Checkout the package that this project is based on for more information on hardware requirements https://github.com/SYSTRAN/faster-whisper.

One thing to note is that I'm not sure whether `faster-whisper-server` will run on ARM as-is. I have built docker images for ARM, but I have never tried running them.

**Comment by thiswillbeyourgithub** [comment]
I have a gtx 1090 i think pretty old but 8go. It hands largev3 faster than using openai's api. Like twice faster

Thanks a lot @fedirz !
