### ISSUE TITLE
Quick Start instructions don't work (yet)

### ISSUE THREAD

**Issue by olinorwell** [fedirz/faster-whisper-server#7]
**The quick start suggestion for Docker Compose:**

curl -sO https://raw.githubusercontent.com/fedirz/faster-whisper-server/master/compose.yaml
docker compose up --detach faster-whisper-server-cuda

**Returns an error:**

failed to solve: failed to read dockerfile: open Dockerfile.cuda: no such file or directory

**It needs to be replaced with:**

git clone https://github.com/fedirz/faster-whisper-server
cd faster-whisper-server
docker compose up --detach faster-whisper-server-cuda

At least until a pre-built version is available.

However - even when building the image it fails at:
Unable to find installation candidates for ctranslate2 (4.3.0)
failed to solve: process "/bin/sh -c poetry install --only main" did not complete successfully: exit code: 1

**Comment by olinorwell** [comment]
While it seems like you have an image on Docker Hub - the docker-compose file does not try to pull from there.

I'm sure it's just a minor issue and easy to fix, but just wanted to point out that currently following your instructions does not work.

**Comment by olinorwell** [comment]
Okay I have found the issue - in compose.yaml you need to change the name of the images, you have the version number and name the wrong way around.

I switched these and it now works.

**Comment by fedirz** [comment]
Thanks for creating the issue! Has been fixed by the latest commit.
