### ISSUE TITLE
FR: Disable model name validation

### ISSUE THREAD

**Issue by samos123** [fedirz/faster-whisper-server#71]
I am passing the following environment variable:
```
WHISPER__MODEL:          Systran/faster-whisper-medium.en
```

However, in the request I set a different model name. This is due to the way our proxy works in https://github.com/substratusai/kubeai

This currently throws the following error:
```
  File "/root/faster-whisper-server/faster_whisper_server/main.py", line 67, in load_model                      
    whisper = WhisperModel(                                                                                     
              ^^^^^^^^^^^^^                                                                                     
  File "/usr/local/lib/python3.12/dist-packages/faster_whisper/transcribe.py", line 139, in __init__            
    model_path = download_model(                                                                                
                 ^^^^^^^^^^^^^^^                                                                                
  File "/usr/local/lib/python3.12/dist-packages/faster_whisper/utils.py", line 78, in download_model
    raise ValueError(                                                                                           ValueError: Invalid model size 'faster-whisper-medium-en-cpu', expected one of: tiny.en, tiny, base.en, base, sm
all.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil
-small.en, distil-large-v3 
```

Expected behavior when WHISPER__MODEL env variable is set:
* The model gets downloaded on startup
* The server responds for any model name OR ability to turn off model name validation

For context, here is the PR I'm working on to enable Faster Whisper Server in KubeAI: https://github.com/substratusai/kubeai/pull/177

**Comment by samos123** [comment]
hmm, the error is coming from faster whisper itself. So I'm leaning towards probably having to solve this inside KubeAI itself.

**Comment by fedirz** [comment]
`faster-whisper` has special handling for the models listed in the error message, for those you can provide just the `name` rather than `owner/name`. For all other ones, you'd need to provide a full name like this `ctranslate2-4you/whisper-tiny-ct2-int8_float32` and not `whisper-tiny-ct2-int8_float32`

**Comment by samos123** [comment]
Note, I've already implemented a workaround in KubeAI by removing the model parameter from the request before sending it to Faster Whisper. So we can also close this issue.

The issue is that in my request body the name is "my-model" and then "my-model" gets sent to faster whisper. I want it to ignore it and just use the model that's set as environment variable through `WHISPER__MODEL`.

I would like the following (note this likely conflicts with needs of other users).

If `WHISPER__MODEL` is set:
* Allow the user to not set any model and have it use model defined in `WHISPER__MODEL`
* Ignore the model parameter in the request (could be a seperate flag)
