### ISSUE TITLE
Unload model after being not used for some time

### ISSUE THREAD

**Issue by hgruber** [fedirz/faster-whisper-server#72]
Unlike to #66 it's probably also a good idea to unload the model after e.g. 300s of not being used.
For ollama server this is the standard. My graphics card uses 40W more of power with any model being loaded.

**Comment by samos123** [comment]
I would like this behind a flag so I can keep the model loaded for improved latency.

**Comment by Foddy** [comment]
Has anyone already found a solution for the problem, similar to how Ollama does it? Unfortunately, my GPU also constantly uses around 45W-50W in idle mode, which becomes quite expensive to operate given the local electricity prices (especially if the model is not used for an extended period) :S

**Comment by fedirz** [comment]
> Has anyone already found a solution for the problem, similar to how Ollama does it? Unfortunately, my GPU also constantly uses around 45W-50W in idle mode, which becomes quite expensive to operate given the local electricity prices (especially if the model is not used for an extended period) :S

FYI, I'm currently working on this

**Comment by fedirz** [comment]
@hgruber I'm aware of this, but unfortunately, this is an upstream issue which doesn't seem resolved yet. See (this)[https://github.com/SYSTRAN/faster-whisper/issues/992]. If you find a workaround, please LMK and I'll implement it.
