### ISSUE TITLE
Segments are empty with verbose JSON

### ISSUE THREAD

**Issue by kassemz** [fedirz/faster-whisper-server#86]
Thanks for the great project, @fedirz !

So the segments are empty when using the verbose JSON format. Everything else is printed like duration, language, text and words but the segments is empty:

````
"language": "english",
"segments":
    [
    ],
"task": "transcribe",
````

Am I missing something?

**Comment by fedirz** [comment]
Does this happen all the time or just in some cases? Consider providing a minimal reproducible example (also pls include your config)

**Comment by fedirz** [comment]
Closing. Please reopen if the issue persists and you can provide a reproducible example.
